# The tomcat base image
FROM tomcat:9.0-jdk8

# Install unzip
RUN apt-get update && \
    apt-get install -y unzip && \
    rm -rf /var/lib/apt/lists/*
# Set environment variables
ENV CONTAINER_NAME="Pega_web1"
ENV RAM_SIZE="2GB"
ENV DISK_SIZE="10GB"

# Set container resources
RUN echo "Container Name: $CONTAINER_NAME"
RUN echo "RAM Size: $RAM_SIZE"
RUN echo "Disk Size: $DISK_SIZE"
# Make app directory within container
RUN mkdir -p /usr/local/tomcat/webapps/prweb

# Copy the Pega .war file to the webapps directory in the container
#COPY --chown=root:root prweb.war /usr/local/tomcat/webapps/prweb.war
COPY  prweb.war ${CATALINA_HOME}/webapps/prweb.war
RUN chmod -R g+rw ${CATALINA_HOME}/webapps/prweb

# Unpack the .war file into the prweb directory
RUN unzip /usr/local/tomcat/webapps/prweb.war -d /usr/local/tomcat/webapps/prweb && \
    rm /usr/local/tomcat/webapps/prweb.war
# Change permissions on the unpacked files
#RUN chmod -R g+rw /usr/local/tomcat/webapps/prweb

# Expose port
EXPOSE 8080
EXPOSE 5432
#COPY --chown=root:root  /prweb ${CATALINA_HOME}/webapps/prweb
#RUN chmod -R g+rw ${CATALINA_HOME}/webapps/prweb
COPY /jdbc_drivers/postgresql-42.6.0.jar ${CATALINA_HOME}/lib/
ENV JDBC_URL="jdbc:postgresql://172.17.0.3:5432/postgres"
ENV JDBC_CLASS="org.postgresql.Driver"
ENV DB_USERNAME="postgres"
ENV DB_PASSWORD="postgres"

# Command to run tomcat server
CMD ["catalina.sh", "run"]
