FROM pegasystems/pega
FROM tomcat:9-jdk11-openjdk-slim
RUN rm -rf /usr/local/tomcat/webapps/*
COPY prweb.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
RUN adduser --disabled-password --gecos '' pegauser
COPY --chown=pegauser:root  prweb ${CATALINA_HOME}/webapps/prweb
RUN chmod -R g+rw ${CATALINA_HOME}/webapps/prweb
COPY --chown=pegauser:root /jdbc_drivers/postgresql-42.1.1.jre7.jar  ${CATALINA_HOME}/lib/
ENV JDBC_URL jdbc:postgresql://172.17.0.3:5432/postgres
ENV JDBC_CLASS org.postgresql.Driver
ENV DB_USERNAME postgres
ENV DB_PASSWORD postgres
CMD ["catalina.sh", "run"]
