version: '3.8'

services:
  pega-web:
    image: pegasystems/pega-ready
    container_name: pega-web
    environment:
      - JDBC_URL=jdbc:postgresql://172.17.0.3:5432/postgres
      - JDBC_CLASS=org.postgresql.Driver
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
    networks:
      - app-network

  pega-stream-1:
    image: pegasystems/pega-ready
    container_name: pega-stream-1
    environment:
      - JDBC_URL=jdbc:postgresql://172.17.0.3:5432/postgres
      - JDBC_CLASS=org.postgresql.Driver
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8083:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
    networks:
      - app-network


  pega-stream-2:
    image: pegasystems/pega-ready
    container_name: pega-stream-2
    environment:
      - JDBC_URL=jdbc:postgresql://172.17.0.3:5432/postgres
      - JDBC_CLASS=org.postgresql.Driver
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8084:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
    networks:
      - app-network


  pega-background:
    image: pegasystems/pega-ready
    container_name: pega-background
    environment:
      - JDBC_URL=jdbc:postgresql://172.17.0.3:5432/postgres
      - JDBC_CLASS=org.postgresql.Driver
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8085:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
    networks:
      - app-network
